# Ory Oathkeeper Access Rules Configuration
# Enterprise-grade authentication and authorization rules for API endpoints

# Health check endpoints (public)
- id: "health-check"
  upstream:
    url: "http://redsys-backend:8080"
    preserve_host: true
  match:
    url: "<^(http://localhost|http://redsys-api-gateway)/health$>"
    methods:
      - GET
  authenticators:
    - handler: "anonymous"
  authorizer:
    handler: "allow"
  mutators:
    - handler: "noop"

# Backend health check (public)
- id: "backend-health"
  upstream:
    url: "http://redsys-backend:8080"
    preserve_host: true
  match:
    url: "<^(http://localhost|http://redsys-api-gateway)/backend-health$>"
    methods:
      - GET
  authenticators:
    - handler: "anonymous"
  authorizer:
    handler: "allow"
  mutators:
    - handler: "noop"



# API documentation endpoints (public)
- id: "api-docs"
  upstream:
    url: "http://redsys-backend:8080"
    preserve_host: true
  match:
    url: "<^(http://localhost|http://redsys-api-gateway)/(docs|openapi\\.yaml)$>"
    methods:
      - GET
  authenticators:
    - handler: "anonymous"
  authorizer:
    handler: "allow"
  mutators:
    - handler: "noop"

# OAuth2 endpoints (public)
- id: "oauth2-endpoints"
  upstream:
    url: "http://redsys-backend:8080"
    preserve_host: true
  match:
    url: "<^(http://localhost|http://redsys-api-gateway)/(login|consent)$>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: "anonymous"
  authorizer:
    handler: "allow"
  mutators:
    - handler: "noop"

# API endpoints - require OAuth2 token (dev: anonymous, prod: oauth2_introspection)
- id: "api-endpoints-dev"
  upstream:
    url: "http://redsys-backend:8080"
    preserve_host: true
  match:
    url: "<^(http://localhost|http://redsys-api-gateway)/api/.*>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: "anonymous"  # DEVELOPMENT ONLY. Use oauth2_introspection for production.
  authorizer:
    handler: "allow"
  mutators:
    - handler: "header"

# PRODUCTION RULE (DISABLED FOR DEVELOPMENT)
# - id: "api-endpoints-prod"
#   upstream:
#     url: "http://redsys-backend:8080"
#     preserve_host: true
#   match:
#     url: "<^(http://localhost|http://redsys-api-gateway)/api/.*>"
#     methods:
#       - GET
#       - POST
#       - PUT
#       - DELETE
#       - PATCH
#   authenticators:
#     - handler: "oauth2_introspection"  # PRODUCTION ONLY. Comment out dev rule above and enable this for prod.
#   authorizer:
#     handler: "allow"
#   mutators:
#     - handler: "header"

# Default deny rule (explicit deny for all unmatched requests)
- id: "default-deny"
  match:
    url: ".*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
  authenticators:
    - handler: "anonymous"
  authorizer:
    handler: "allow"  # Changed from "deny" to "allow" since "deny" authorizer is not configured
  mutators:
    - handler: "noop" 