- id: "health-endpoint"
  upstream:
    url: "http://backend:8080"
    preserve_host: true
  match:
    url: "http://oathkeeper:4455/health"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "backend-health-endpoint"
  upstream:
    url: "http://backend:8080"
    preserve_host: true
  match:
    url: "http://oathkeeper:4455/backend-health"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "public-api-endpoints"
  upstream:
    url: "http://backend:8080"
    preserve_host: true
  match:
    url: "http://oathkeeper:4455/api/v1/hello"
    methods:
      - GET
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "authenticated-api-endpoints"
  upstream:
    url: "http://backend:8080"
    preserve_host: true
  match:
    url: "http://oathkeeper:4455/api/v1/users"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header

- id: "providers-api"
  upstream:
    url: "http://backend:8080"
    preserve_host: true
  match:
    url: "http://oathkeeper:4455/api/v1/providers"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header

- id: "jobs-api"
  upstream:
    url: "http://backend:8080"
    preserve_host: true
  match:
    url: "http://oathkeeper:4455/api/v1/jobs"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header

- id: "oauth2-login"
  upstream:
    url: "http://backend:8080"
    preserve_host: true
  match:
    url: "http://oathkeeper:4455/login"
    methods:
      - GET
      - POST
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "oauth2-consent"
  upstream:
    url: "http://backend:8080"
    preserve_host: true
  match:
    url: "http://oathkeeper:4455/consent"
    methods:
      - GET
      - POST
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop 